version: '3.7'
# Default ${TEAMCITY_VERSION} is defined in .env file

services:
  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8112:8111"
    volumes:
      - ../apps_data/teamcity:/data/teamcity_server/datadir
      - ../logs/teamcity-server-logs:/opt/teamcity/logs
    environment:
      - TEAMCITY_SERVER_OPTS="-Dteamcity.csrf.origin.check.enabled=logOnly"


  teamcity-agent:
    depends_on:
      - teamcity
    image: jetbrains/teamcity-minimal-agent:${TEAMCITY_VERSION}
    privileged: true
    volumes:
      - ../config/agent:/data/teamcity_agent/conf